### ISSUE TITLE
your readme sucks ... 

### ISSUE THREAD

**Issue by ddarvish** [EnigmaCurry/GMusicFS#40]
the documentation on how to install and use is really lacking like shit.. why the hell bother if you are gonna half ass it. someone needs to write out DETAILED step by step install instructions. once i have everything installed where am i creating a config file? 
what should be the name of the config file?
why is ~/.gmusicfs different than /root/.gmusicfs ?

some better documentation for use beginners would be nice

root@localhost:~# gmusicfs --deviceid
Traceback (most recent call last):
  File "/usr/local/bin/gmusicfs", line 9, in <module>
    load_entry_point('GMusicFS==0.1', 'console_scripts', 'gmusicfs')()
  File "/usr/local/lib/python2.7/dist-packages/gmusicfs/gmusicfs.py", line 426, in main
    getDeviceId()
  File "/usr/local/lib/python2.7/dist-packages/gmusicfs/gmusicfs.py", line 389, in getDeviceId
    % cred_path)
gmusicfs.gmusicfs.NoCredentialException: No username/password was specified. No config file could be found either. Try creating /root/.gmusicfs and specifying your username/password there. Make sure to chmod 600.
root@localhost:~# ls
config  gmusicfs  tmp
root@localhost:~# cd ./gmusicfs/
root@localhost:~/gmusicfs# ls
root@localhost:~/gmusicfs#

**Comment by EnigmaCurry** [comment]
Thank you for your kind words, but I think we are on different paths. On mine, I share things I think are cool. But I also move on. Sometimes I retrace a favorite path. Sometimes I encounter remarkable people.
